# Basic parameters
feat_eval_folder: /home/abc000/data/feat_eval/ # dir to store eval feature
feat_norm_folder:  /home/abc000/data/feat_norm/ # dir to store norm feature
data_folder: /home/abc000/data/voxceleb1/ # data folder
output_folder: /home/abc000/data/data_aug_eval/
save_folder: !ref <output_folder>/save/
device: 'cpu'

verification_file: /home/abc000/data/voxceleb1/veri_test2.txt
verification_file_bleeched: !ref <feat_eval_folder>/veri_test_bleeched.txt
skip_prep: false

# csv files
train_data: !ref <save_folder>/train.csv
enrol_data: !ref <save_folder>/enrol.csv
test_data: !ref <save_folder>/test.csv

batch_size: 1
score_norm: 's-norm'
n_train_snts: 400000 # used for normalization stats

# Feature parameters
n_mels: 80
left_frames: 0
right_frames: 0
deltas: False

# Dataloader options
train_dataloader_opts:
    batch_size: 1

enrol_dataloader_opts:
    batch_size: 1

test_dataloader_opts:
    batch_size: 1

compute_features: !new:speechbrain.lobes.features.Fbank
    n_mels: 80

mean_var_norm: !new:speechbrain.processing.features.InputNormalization
    norm_type: sentence
    std_norm: False


